// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/ONSdigital/dp-feedback-api/service"
	"sync"
)

// Ensure, that EmailSenderMock does implement service.EmailSender.
// If this is not the case, regenerate this file with moq.
var _ service.EmailSender = &EmailSenderMock{}

// EmailSenderMock is a mock implementation of service.EmailSender.
//
//	func TestSomethingThatUsesEmailSender(t *testing.T) {
//
//		// make and configure a mocked service.EmailSender
//		mockedEmailSender := &EmailSenderMock{
//			SendFunc: func(from string, to []string, msg []byte) error {
//				panic("mock out the Send method")
//			},
//		}
//
//		// use mockedEmailSender in code that requires service.EmailSender
//		// and then make assertions.
//
//	}
type EmailSenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(from string, to []string, msg []byte) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// From is the from argument value.
			From string
			// To is the to argument value.
			To []string
			// Msg is the msg argument value.
			Msg []byte
		}
	}
	lockSend sync.RWMutex
}

// Send calls SendFunc.
func (mock *EmailSenderMock) Send(from string, to []string, msg []byte) error {
	if mock.SendFunc == nil {
		panic("EmailSenderMock.SendFunc: method is nil but EmailSender.Send was just called")
	}
	callInfo := struct {
		From string
		To   []string
		Msg  []byte
	}{
		From: from,
		To:   to,
		Msg:  msg,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(from, to, msg)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEmailSender.SendCalls())
func (mock *EmailSenderMock) SendCalls() []struct {
	From string
	To   []string
	Msg  []byte
} {
	var calls []struct {
		From string
		To   []string
		Msg  []byte
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}
